language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2
before_install:
- openssl aes-256-cbc -K $encrypted_92b93fb23917_key -iv $encrypted_92b93fb23917_iv
  -in semi-186012-d811e69bf044.json.enc -out semi-186012-d811e69bf044.json -d
