sudo: required
language: java
jdk:
- oraclejdk8
services:
- docker
env:
  global:
  - GOOGLE_APPLICATION_CREDENTIALS="${PWD}/semi-weaviate-infra.json"
  - PROJECT_ID="semi-186012"
  - ZONE="europe-west1-b"
  - TF_VERSION="0.11.0"
  - TF_VAR_gke_project="semi-186012"
  - TF_VAR_cluster_name="weaviate-${TRAVIS_BUILD_ID}-${TRAVIS_BUILD_NUMBER}"
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
before_install:
- openssl aes-256-cbc -K $encrypted_92b93fb23917_key -iv $encrypted_92b93fb23917_iv -in semi-186012-d811e69bf044.json.enc -out semi-weaviate-infra.json -d

# Install GCloud SDK
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
# Add gcloud to $PATH
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version

- gcloud components update kubectl --quiet
- gcloud auth activate-service-account --key-file "${GOOGLE_APPLICATION_CREDENTIALS}"
- gcloud config set project $PROJECT_ID
- gcloud config set compute/zone $ZONE

# Install Terraform
- curl -sLo /tmp/terraform.zip "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
- unzip /tmp/terraform.zip -d /tmp
- mv /tmp/terraform ~/bin/
- export PATH="~/bin:$PATH"

install: true
script:
# Create GKE cluster
- terraform init ./terraform
- terraform plan ./terraform
- terraform apply -auto-approve ./terraform
# Prepare Cluster
- gcloud container clusters get-credentials ${TF_VAR_cluster_name}
- ./helm_setup.sh
# Deploy Weaviate
- helm package ./helm/weaviate
- helm install --name weaviate ./weaviate-0.0.1.tgz
after_script:
- terraform destroy -force ./terraform
