apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    app: verification
  name: verification
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: verification
    spec:
      containers:
      - image: creativesoftwarefdn/weaviate-verification
        name: verification
        # -t = Number of Thing Classes in the ontology
        # -r = Number of Classes that cross-references other classes
        # -a = Number of Action Classes in the ontology
        # -v = Number of vertices (Things and Actions) to be generated
        # -c = checks
        args: ["generate", "-t", "128", "-r", "128", "-a", "128", "-v", "1280", "-c", "640", "-w", "http://weaviate:80"]
      restartPolicy: OnFailure
