dependencies:
  - name: janusgraph
    version: 0.2.0
    repository: "@stable"
    alias: janusgraph

  - name: elasticsearch
    version: 1.11.1
    repository: "@stable"
    alias: elasticsearch
    condition: elasticsearch.deploy

  - name: cassandra
    version: 0.9.0
    repository: "@incubator"
    alias: cassandra
    condition: cassandra.deploy
