# Global values
global:
  db: cassandra
  index: elasticsearch

# Related to the weaviate image
image:
  # registry where weaviate image is stored
  registry: docker.io/
  # tag of image to deploy
  tag: unstable

importer: false

autoscaling:
  enabled: true
  cpuTargetPercentage: 70
  replicas: 0
  replicasMax: 50
  replicasMin: 1

# Weaviate Config
initialKey: 657a48b9-e000-4d9a-b51d-69a0b621c1b9
initialToken: 57ac8392-1ecc-4e17-9350-c9c866ac832b
contextionary:
  knnFile: /contextionary/contextionary.knn
  idxFile: /contextionary/contextionary.idx

etcdOperator:
  deploy: false

# Etcd Cluster
etcdCluster:
  create: true
  name: weaviate-etcd
  size: 5
  version: 3.2.25
  pod:
    resources:
      requests:
        memory: 256Mi
        cpu: 0.25
      limits:
        memory: 1Gi
        cpu: 1

# Sub Chart Overrides

#Cassandra
cassandra:
  livenessProbe:
    initialDelaySeconds: 60
  readinessProbe:
    initialDelaySeconds: 60
  deploy: true
  image:
    tag: 3
  config:
    cluster_size: 3
    seed_size: 2
    start_rpc: true
  resources:
    requests:
      memory: 2Gi
      cpu: 1
    limits:
      memory: 8Gi
      cpu: 4

#Elasticsearch
elasticsearch:
  deploy-so: true
  master:
    replicas: 5
  client:
    replicas: 5
  data:
    replicas: 5
  cluster:
    env: 
      MINIMUM_MASTER_NODES: "2"

#Janus
janusgraph:
  image:
    repository: creativesoftwarefdn/janusgraph-docker
    tag: 0.2.2
  elasticsearch.deploy:
    deploy: false
  configMapOverrideName: janusgraph-config
  replicaCount: 5
  resources:
    requests:
      memory: 1Gi
      cpu: 0.5
    limits:
      memory: 8Gi
      cpu: 4
  persistence:
    enabled: false
  properties:
    storage.backend: cassandra
    storage.directory: /db/cassandra
    storage.hostname: weaviate-cassandra
    storage.batch-loading: true
    gremlin.graph: org.janusgraph.core.JanusGraphFactory
    index.search.elasticsearch.interface: REST_CLIENT
    index.search.backend: elasticsearch
    index.search.hostname: weaviate-elasticsearch-client
    storage.index.search.local-mode: false
    storage.index.search.client-only: false
    query.force-index: true
