# Global values
global:
  db: cassandra
  index: elasticsearch

# Related to the weaviate image
image:
  # registry where weaviate image is stored
  registry: docker.io/
  # tag of image to deploy
  tag: unstable

importer: false

autoscaling:
  enabled: true
  cpuTargetPercentage: 70
  replicas: 8
  replicasMax: 50
  replicasMin: 1

# Weaviate Config
initialKey: 657a48b9-e000-4d9a-b51d-69a0b621c1b9
initialToken: 57ac8392-1ecc-4e17-9350-c9c866ac832b
contextionary:
  knnFile: /contextionary/contextionary.knn
  idxFile: /contextionary/contextionary.idx

etcdOperator:
  deploy: false

# Etcd Cluster
etcdCluster:
  create: true
  name: weaviate-etcd
  size: 6
  version: 3.2.25
  pod:
    resources:
      requests:
        memory: 8Gi
        cpu: 2
      limits:
        memory: 16Gi
        cpu: 4

# Sub Chart Overrides

#Cassandra
cassandra:
  persistence:
    size: 200Gi
  livenessProbe:
    initialDelaySeconds: 60
  readinessProbe:
    initialDelaySeconds: 60
  deploy: true
  image:
    tag: 3
  config:
    cluster_size: 18
    seed_size: 2
    start_rpc: true
    max_heap_size: 8096M
    heap_new_size: 2048M
  resources:
    requests:
      memory: 12Gi
      cpu: 4
    limits:
      memory: 16Gi
      cpu: 8

#Elasticsearch
elasticsearch:
  deploy-so: true
  master:
    replicas: 3
  client:
    replicas: 3
  data:
    replicas: 15
    heapSize: 4096M
    resources: 
      requests:
        cpu: 1
        memory: 4Gi
      limits:
        cpu: 4
        memory: 8Gi
  cluster:
    env: 
      MINIMUM_MASTER_NODES: "2"

#Janus
janusgraph:
  image:
    repository: creativesoftwarefdn/janusgraph-docker
    tag: 0.2.2
  configMapOverrideName: janusgraph-config
  replicaCount: 3
  resources:
    requests:
      memory: 4Gi
      cpu: 0.5
    limits:
      memory: 8Gi
      cpu: 4
  persistence:
    enabled: false
  properties:
    storage.backend: cassandra
    storage.directory: /db/cassandra
    storage.hostname: weaviate-cassandra
    storage.batch-loading: true
    storage.cassandra.replication-factor: 3
    storage.cassandra.write-consistency-level: ONE
    gremlin.graph: org.janusgraph.core.JanusGraphFactory
    index.search.elasticsearch.interface: REST_CLIENT
    index.search.backend: elasticsearch
    index.search.hostname: weaviate-elasticsearch-client
    storage.index.search.local-mode: false
    storage.index.search.client-only: false
    storage.buffer-size: 4096
    query.force-index: true

#Spark
spark:
  master:
    resources:
      requests:
        memory: 1.5Gi
        cpu: 0.5
      limits:
        memory: 2Gi
        cpu: 2
  worker:
    replicas: 1
    resources:
      requests:
        memory: 1.5Gi
        cpu: 0.5
      limits:
        memory: 2Gi
        cpu: 2
