{{- if ( .Values.spark.deploy) -}}
apiVersion: v1
kind: Service
metadata:
  name: janus-spark-analytics
spec:
  selector:
    app: janus-spark-analytics
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
{{- end -}}
