apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: weaviate
  labels:
    name: weaviate
spec:
  progressDeadlineSeconds: 1200
  template:
    metadata:
      labels:
        app: weaviate
    spec:
      containers:
      - name: weaviate
        image: {{ .Values.image.registry }}creativesoftwarefdn/weaviate:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        args: [ "--host", "0.0.0.0", "--port", "8080", "--scheme", "http", "--config", "default", "--config-file", "/weaviate-config/weaviate.conf.yaml"]
        volumeMounts:
        - name: weaviate-config
          mountPath: /weaviate-config
      volumes:
      - name: weaviate-config
        configMap:
          name: weaviate-config
