{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: weaviate
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: weaviate
  minReplicas: {{ .Values.autoscaling.replicasMin }}
  maxReplicas: {{ .Values.autoscaling.replicasMax }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.autoscaling.cpuTargetPercentage }}
{{- end }}