apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: scylladb/scylla:2.0.1
        name: db
        ports:
        - containerPort: 10000
        - containerPort: 9042
        - containerPort: 9160
        - containerPort: 7000
        - containerPort: 7001
        - containerPort: 7199
        - containerPort: 9180
        - containerPort: 9100
        volumeMounts:
        - mountPath: /var/lib/scylla
          name: db-claim
      volumes:
      - name: db-claim
        persistentVolumeClaim:
          claimName: db-claim
