apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: weaviate-demo-importer
  name: weaviate-demo-importer
spec:
  template:
    metadata:
      labels:
        app: weaviate-demo-importer
    spec:
      containers:
      - args:
        - -weaviate-url
        - http://weaviate:8080/weaviate/v1/
        image: creativesoftwarefdn/weaviate-demo-importer:0.0.1
        name: weaviate-demo-importer
      restartPolicy: OnFailure
