apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: weaviate
  name: weaviate
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: weaviate
    spec:
      containers:
      - image: creativesoftwarefdn/weaviate:unstable
        name: weaviate
        ports:
        - containerPort: 8080
